#######################################################################################
# Name: Deploy Fabric Items Push
# Description: This workflow deploys Microsoft Fabric items to target workspace.
#######################################################################################
on:
  push:
    branches:
      - main
      - develop
      - feature/*

env:
  dotnet-version: '8.0.x'

name: Deploy Fabric Items

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup dotnet ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: Display dotnet version
        run: |
          dotnet --version